# Generated by Django 5.1.3 on 2025-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='телефон')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'подписчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
    ]
