# Generated by Django 5.1.3 on 2024-12-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='почта клиента')),
                ('client_name', models.CharField(max_length=50, verbose_name='имя клиента')),
                ('client_phone', models.CharField(max_length=11, verbose_name='телефон клиента')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table', verbose_name='стол')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'бронь',
            },
        ),
    ]
