# Generated by Django 5.1.3 on 2024-12-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_time_from_alter_booking_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='призник уведомления'),
        ),
    ]
