# Generated by Django 5.1.3 on 2024-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='признак уведомления'),
        ),
    ]
