# Generated by Django 5.1.3 on 2025-01-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_is_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsequence', models.PositiveIntegerField(default=1, verbose_name='последовательность')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('reversed', models.BooleanField(default=False, verbose_name='отзеркалено')),
            ],
            options={
                'verbose_name': 'контент',
                'verbose_name_plural': 'контент',
            },
        ),
    ]
