# Generated by Django 5.1.3 on 2025-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.AddField(
            model_name='content',
            name='text1',
            field=models.TextField(blank=True, null=True, verbose_name='текст1'),
        ),
        migrations.AddField(
            model_name='content',
            name='text2',
            field=models.TextField(blank=True, null=True, verbose_name='текст2'),
        ),
        migrations.AddField(
            model_name='content',
            name='text3',
            field=models.TextField(blank=True, null=True, verbose_name='текст3'),
        ),
    ]
