# Generated by Django 5.1.3 on 2025-01-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_content_text_content_text1_content_text2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='номер стола'),
        ),
    ]
